WITH RAW AS
(
    SELECT * FROM {{ source('azure_files_load', 'claims') }}
)
SELECT
CLAIM_ID,
MEMBER_ID,
PROVIDER_ID,
TRY_TO_DATE(SERVICE_DATE) AS SERVICE_DATE,
TRY_TO_NUMBER(CLAIM_AMOUNT,10,2) AS  CLAIM_AMOUNT,
UPPER(CLAIM_TYPE) AS CLAIM_TYPE,
UPPER(CLAIM_STATUS) AS CLAIM_STATUS,
SOURCE_SYSTEM
FROM
RAW
WHERE CLAIM_TYPE IN ('OUTPATIENT','INPATIENT')