name: Healthcare DW Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bronze_ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI
        run: |
          pip install --upgrade pip
          pip install --user snowflake-cli
          echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH

      - name: Run Snowflake Stored Procedure
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          snowflakecli sql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD \
          -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -s $SNOWFLAKE_SCHEMA \
          -q "CALL OPS.SP_FILE_INGEST_DUMP();"

  dbt_transform:
    runs-on: ubuntu-latest
    needs: bronze_ingest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-core dbt-snowflake

      - name: Run dbt Silver models
        run: dbt run --select silver/*

      - name: Run dbt Gold models
        run: dbt run --select gold/*

      - name: Run dbt tests
        run: dbt test
