name: Healthcare DW Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bronze_ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI
        run: |
          pip install --upgrade pip
          pip install --user snowflake-cli
          echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
          export PATH="$(python -m site --user-base)/bin:$PATH"

      - name: Run Snowflake Stored Procedure
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_HOST: ${{ secrets.SNOWFLAKE_HOST }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: snow sql --query "CALL OPS.SP_FILE_INGEST_DUMP();"

  dbt_transform:
    runs-on: ubuntu-latest
    needs: bronze_ingest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install --user -r requirements.txt
          echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
          export PATH="$(python -m site --user-base)/bin:$PATH"

      - name: Run dbt models
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_HOST: ${{ secrets.SNOWFLAKE_HOST }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWSQL_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          dbt run --select silver/*
          dbt run --select gold/*
          dbt test
